# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /opt/bitnami/projects/edgar-web-public
    overwrite: true

hooks:
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300